# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: ci-test

# Define triggers, which are push to master branch or if there is a Pull Request in master branch
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  
  # job 1
  build:
    runs-on: ubuntu-latest # Runner info

    # Step 1 to checkout the code of this repo
    steps:
    - uses: actions/checkout@v4
      
    # Step 2 to install go on the runner
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Test
      run: make test
